# Generated by Django 3.2 on 2023-09-01 08:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='symbol',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='party_symbol'),
        ),
    ]
