# Generated by Django 3.2 on 2023-09-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('voting', '0002_alter_party_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='halka',
            field=models.ForeignKey(default='Mardan', on_delete=django.db.models.deletion.CASCADE, to='account.halka'),
        ),
    ]
