# Generated by Django 3.2 on 2023-09-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('voting', '0003_alter_candidate_halka'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='polling_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.pollingschedule'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='halka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.halka'),
        ),
    ]
