# Generated by Django 3.2 on 2023-08-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_halka'),
        ('voting', '0004_vote_halka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='vote',
            name='halka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.halka'),
        ),
    ]
